# Generated by Django 5.2.17 on 2026-10-05 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("contracting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="الفئة")),
                (
                    "life_months",
                    models.PositiveIntegerField(
                        default=60, verbose_name="العمر الافتراضي (شهر)"
                    ),
                ),
                (
                    "accum_account",
                    models.ForeignKey(
                        limit_choices_to={"is_group": False},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="حساب مجمع الإهلاك",
                    ),
                ),
                (
                    "asset_account",
                    models.ForeignKey(
                        limit_choices_to={"is_group": False},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="حساب الأصل",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        limit_choices_to={"is_group": False},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="حساب مصروف الإهلاك",
                    ),
                ),
            ],
            options={
                "verbose_name": "فئة أصول",
                "verbose_name_plural": "فئات الأصول",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="الكود"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الأصل")),
                ("purchase_date", models.DateField(verbose_name="تاريخ الشراء")),
                ("start_date", models.DateField(verbose_name="بداية الإهلاك")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="تكلفة الشراء"
                    ),
                ),
                (
                    "salvage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="القيمة التخريدية",
                    ),
                ),
                (
                    "life_months",
                    models.PositiveIntegerField(verbose_name="العمر الافتراضي (شهر)"),
                ),
                (
                    "opening_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="إهلاك سابق (رصيد افتتاحي)",
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="الرقم المسلسل / اللوحة"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=120, verbose_name="المكان"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "قيد الاستخدام"),
                            ("depreciated", "مُهلك بالكامل"),
                            ("disposed", "مُستبعد"),
                        ],
                        default="running",
                        max_length=12,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracting.project",
                        verbose_name="يُحمل على مشروع",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="assets.assetcategory",
                        verbose_name="الفئة",
                    ),
                ),
            ],
            options={
                "verbose_name": "أصل ثابت",
                "verbose_name_plural": "الأصول الثابتة",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("posted", "مرحّل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="الرقم"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاريخ الإهلاك (نهاية الشهر)")),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="البيان"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                        verbose_name="القيد",
                    ),
                ),
            ],
            options={
                "verbose_name": "قيد إهلاك",
                "verbose_name_plural": "قيود الإهلاك",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="المبلغ"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dep_lines",
                        to="assets.asset",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="assets.depreciationrun",
                    ),
                ),
            ],
        ),
    ]
