-- نبضٌ صغير — جداول قاعدة البيانات (MySQL). شغّليها مرة واحدة من phpMyAdmin ← Import
CREATE TABLE IF NOT EXISTS questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dev VARCHAR(64) NOT NULL,
  nick VARCHAR(40) NOT NULL DEFAULT '',
  anon TINYINT NOT NULL DEFAULT 0,
  cat VARCHAR(16) NOT NULL DEFAULT 'other',
  title VARCHAR(160) NOT NULL,
  body TEXT NOT NULL,
  stage VARCHAR(80) NOT NULL DEFAULT '',
  t BIGINT NOT NULL,
  ac INT NOT NULL DEFAULT 0,
  reports INT NOT NULL DEFAULT 0,
  hidden TINYINT NOT NULL DEFAULT 0,
  ip VARCHAR(64) NOT NULL DEFAULT '',
  INDEX (t)
) DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS answers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  qid INT NOT NULL,
  dev VARCHAR(64) NOT NULL,
  nick VARCHAR(40) NOT NULL DEFAULT '',
  anon TINYINT NOT NULL DEFAULT 0,
  ai TINYINT NOT NULL DEFAULT 0,
  body TEXT NOT NULL,
  stage VARCHAR(80) NOT NULL DEFAULT '',
  t BIGINT NOT NULL,
  hp INT NOT NULL DEFAULT 0,
  reports INT NOT NULL DEFAULT 0,
  hidden TINYINT NOT NULL DEFAULT 0,
  ip VARCHAR(64) NOT NULL DEFAULT '',
  INDEX (qid)
) DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ref VARCHAR(64) NOT NULL,
  dev VARCHAR(64) NOT NULL,
  t BIGINT NOT NULL,
  UNIQUE KEY one_report (ref, dev)
) DEFAULT CHARSET=utf8mb4;
-- بلاغات ردود المساعد الذكي (المحتوى المولَّد بالذكاء الاصطناعي)
CREATE TABLE IF NOT EXISTS ai_reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dev VARCHAR(64) NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  reason VARCHAR(40) NOT NULL,
  note VARCHAR(500) NOT NULL DEFAULT '',
  t BIGINT NOT NULL,
  INDEX (t)
) DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS bans (
  dev VARCHAR(64) PRIMARY KEY,
  t BIGINT NOT NULL
) DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS usage_log (
  k VARCHAR(100) PRIMARY KEY,
  n INT NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8mb4;
-- الحسابات: دخول برمز على الإيميل وحفظ البيانات لاسترجاعها على جوال آخر
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(120) NOT NULL UNIQUE,
  created BIGINT NOT NULL,
  data MEDIUMTEXT NULL,
  updated BIGINT NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS auth_codes (
  email VARCHAR(120) PRIMARY KEY,
  code VARCHAR(255) NOT NULL,
  exp INT NOT NULL,
  tries INT NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sessions (
  token CHAR(64) PRIMARY KEY,
  uid INT NOT NULL,
  t BIGINT NOT NULL,
  INDEX (uid)
) DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS user_photos (
  uid INT NOT NULL,
  k VARCHAR(20) NOT NULL,
  sig VARCHAR(40) NOT NULL DEFAULT '',
  data MEDIUMTEXT NOT NULL,
  PRIMARY KEY (uid, k)
) DEFAULT CHARSET=utf8mb4;
