from django.urls import path

from . import reports, views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("accounts/", views.account_tree, name="account_tree"),
    path("accounts/new/", views.account_form, name="account_new"),
    path("accounts/<int:pk>/", views.account_form, name="account_edit"),
    path("accounts/<int:pk>/delete/", views.account_delete, name="account_delete"),
    path("cost-centers/", views.cost_center_list, name="cost_center_list"),
    path("cost-centers/new/", views.cost_center_form),
    path("cost-centers/<int:pk>/", views.cost_center_form),
    path("taxes/", views.tax_list, name="tax_list"),
    path("taxes/new/", views.tax_form),
    path("taxes/<int:pk>/", views.tax_form),
    path("partners/", views.partner_list, name="partner_list"),
    path("partners/new/", views.partner_form),
    path("partners/<int:pk>/", views.partner_detail, name="partner_detail"),
    path("partners/<int:pk>/edit/", views.partner_form),
    path("journal/", views.journal_list, name="journal_list"),
    path("journal/new/", views.journal_form, name="journal_new"),
    path("journal/<int:pk>/", views.journal_detail, name="journal_detail"),
    path("journal/<int:pk>/edit/", views.journal_form, name="journal_edit"),
    path("journal/<int:pk>/<str:action>/", views.journal_action, name="journal_action"),
    path("journal/templates/", views.template_list, name="template_list"),
    path("journal/templates/new/", views.template_form),
    path("journal/templates/<int:pk>/edit/", views.template_form),
    path("journal/templates/<int:pk>/use/", views.template_use, name="template_use"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/mapping/", views.mapping_view, name="mapping"),
    path("settings/close-year/", views.year_close, name="year_close"),
    path("settings/backup/", views.backup, name="backup"),
    path("reports/", reports.reports_index, name="reports"),
    path("reports/trial-balance/", reports.trial_balance, name="trial_balance"),
    path("reports/ledger/", reports.account_ledger, name="account_ledger"),
    path("reports/partner-statement/", reports.partner_statement, name="partner_statement"),
    path("reports/partner-statement/<int:pk>/", reports.partner_statement),
    path("reports/income-statement/", reports.income_statement, name="income_statement"),
    path("reports/balance-sheet/", reports.balance_sheet, name="balance_sheet"),
    path("reports/taxes/", reports.tax_report, name="tax_report"),
    path("reports/aging/", reports.aging, name="aging"),
    path("reports/cost-centers/", reports.cost_center_report, name="cost_center_report"),
]
