# Generated by Django 5.2.17 on 2026-10-05 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="شركتي للمقاولات",
                        max_length=200,
                        verbose_name="اسم الشركة",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الاسم القانوني"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم التسجيل الضريبي"
                    ),
                ),
                (
                    "commercial_reg",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="السجل التجاري"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="العنوان"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="التليفون"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="ج.م", max_length=10, verbose_name="العملة"
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(
                        default="جنيه", max_length=30, verbose_name="اسم العملة"
                    ),
                ),
                (
                    "currency_sub",
                    models.CharField(
                        default="قرش", max_length=30, verbose_name="اسم الكسر"
                    ),
                ),
                (
                    "fiscal_year_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="بداية السنة المالية"
                    ),
                ),
                (
                    "lock_date",
                    models.DateField(
                        blank=True,
                        help_text="لا يُسمح بإنشاء أو تعديل أي قيد بتاريخ يساوي أو يسبق هذا التاريخ",
                        null=True,
                        verbose_name="تاريخ إقفال الفترات",
                    ),
                ),
            ],
            options={
                "verbose_name": "الشركة",
            },
        ),
        migrations.CreateModel(
            name="JournalTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم النموذج")),
                (
                    "memo",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="البيان الافتراضي"
                    ),
                ),
                (
                    "ask_partner",
                    models.BooleanField(default=False, verbose_name="يتطلب جهة تعامل"),
                ),
                (
                    "ask_project",
                    models.BooleanField(default=False, verbose_name="يتطلب مشروع"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "قيد جاهز",
                "verbose_name_plural": "القيود الجاهزة",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JournalTemplateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("debit", "مدين"), ("credit", "دائن")],
                        max_length=6,
                        verbose_name="الجانب",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=100,
                        max_digits=7,
                        verbose_name="نسبة من المبلغ %",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=200, verbose_name="البيان"),
                ),
                (
                    "use_partner",
                    models.BooleanField(default=False, verbose_name="يحمل جهة التعامل"),
                ),
                (
                    "use_project",
                    models.BooleanField(default=False, verbose_name="يحمل المشروع"),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, verbose_name="الكود"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="الاسم")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("customer", "عميل"),
                            ("supplier", "مورد"),
                            ("subcontractor", "مقاول باطن"),
                            ("both", "عميل ومورد"),
                            ("employee", "موظف"),
                            ("other", "أخرى"),
                        ],
                        default="customer",
                        max_length=15,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم التسجيل الضريبي"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الرقم القومي / السجل"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="التليفون"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="العنوان"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="حد الائتمان",
                    ),
                ),
                (
                    "payment_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مدة السداد (يوم)"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="نشط")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "جهة تعامل",
                "verbose_name_plural": "العملاء والموردون",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("prefix", models.CharField(max_length=20)),
                ("next_number", models.PositiveIntegerField(default=1)),
                ("padding", models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vat", "ضريبة قيمة مضافة"),
                            ("wht", "خصم من المنبع (خصم وإضافة)"),
                        ],
                        max_length=5,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="النسبة %"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("sale", "مبيعات"),
                            ("purchase", "مشتريات"),
                            ("both", "الكل"),
                        ],
                        default="both",
                        max_length=10,
                        verbose_name="النطاق",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "ضريبة",
                "verbose_name_plural": "الضرائب",
                "ordering": ["kind", "rate"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="الكود"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الحساب")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("asset", "أصول"),
                            ("liability", "خصوم"),
                            ("equity", "حقوق ملكية"),
                            ("income", "إيرادات"),
                            ("expense", "مصروفات وتكاليف"),
                        ],
                        max_length=10,
                        verbose_name="نوع الحساب",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("other", "عادي"),
                            ("cash", "خزينة / نقدية"),
                            ("bank", "بنك"),
                            ("receivable", "عملاء / مدينون"),
                            ("payable", "موردون / دائنون"),
                        ],
                        default="other",
                        max_length=12,
                        verbose_name="طبيعة خاصة",
                    ),
                ),
                (
                    "is_group",
                    models.BooleanField(
                        default=False, verbose_name="حساب تجميعي (لا يقبل قيود)"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="ملاحظات"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="accounting.account",
                        verbose_name="الحساب الرئيسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب",
                "verbose_name_plural": "شجرة الحسابات",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccountMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("receivable", "حساب العملاء الافتراضي"),
                            ("payable", "حساب الموردين الافتراضي"),
                            ("subcontractor_payable", "حساب مقاولي الباطن"),
                            ("sales", "إيرادات المبيعات"),
                            ("sales_return", "مردودات المبيعات"),
                            ("purchase", "المشتريات / المصروفات الافتراضية"),
                            ("inventory", "المخزون"),
                            ("cogs", "تكلفة البضاعة المباعة"),
                            ("project_materials", "تكلفة مواد المشروعات (صرف مخزني)"),
                            ("stock_adjustment", "فروق جرد وتسويات المخزون"),
                            ("vat_out", "ضريبة القيمة المضافة - مخرجات (مبيعات)"),
                            ("vat_in", "ضريبة القيمة المضافة - مدخلات (مشتريات)"),
                            (
                                "wht_receivable",
                                "ضرائب خصم من المنبع مخصومة منا (مدينة)",
                            ),
                            (
                                "wht_payable",
                                "ضريبة الخصم والإضافة المستحقة علينا (دائنة)",
                            ),
                            ("customer_advance", "دفعات مقدمة من العملاء"),
                            ("supplier_advance", "دفعات مقدمة للموردين ومقاولي الباطن"),
                            ("retention_receivable", "محتجزات ضمان أعمال لدى العملاء"),
                            ("retention_payable", "محتجزات ضمان أعمال مقاولي الباطن"),
                            ("contract_revenue", "إيرادات مستخلصات المشروعات"),
                            ("subcontract_cost", "تكلفة أعمال مقاولي الباطن"),
                            (
                                "social_ins_expense",
                                "تأمينات اجتماعية مخصومة من مستخلصاتنا (مصروف)",
                            ),
                            (
                                "social_ins_payable",
                                "تأمينات اجتماعية مخصومة من مقاولي الباطن (مستحقة)",
                            ),
                            ("retained_earnings", "الأرباح المرحلة"),
                            ("opening_equity", "أرصدة افتتاحية"),
                            ("discount_allowed", "خصم مسموح به"),
                            ("discount_received", "خصم مكتسب"),
                        ],
                        max_length=40,
                        unique=True,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.account",
                        verbose_name="الحساب",
                    ),
                ),
            ],
            options={
                "verbose_name": "توجيه محاسبي",
                "verbose_name_plural": "التوجيه المحاسبي",
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="الكود"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم")),
                ("active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="accounting.costcenter",
                        verbose_name="المركز الرئيسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "مركز تكلفة",
                "verbose_name_plural": "مراكز التكلفة",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="رقم القيد"
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "reference",
                    models.CharField(blank=True, max_length=100, verbose_name="المرجع"),
                ),
                ("memo", models.CharField(max_length=300, verbose_name="البيان")),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "مسودة"), ("posted", "مرحّل")],
                        default="draft",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "قيد يومية يدوي"),
                            ("opening", "قيد افتتاحي"),
                            ("closing", "قيد إقفال"),
                            ("sale", "فاتورة مبيعات"),
                            ("sale_return", "مردود مبيعات"),
                            ("purchase", "فاتورة مشتريات"),
                            ("purchase_return", "مردود مشتريات"),
                            ("receipt", "سند قبض"),
                            ("payment", "سند صرف"),
                            ("transfer", "تحويل نقدية"),
                            ("stock", "حركة مخزنية"),
                            ("depreciation", "إهلاك"),
                            ("client_cert", "مستخلص عميل"),
                            ("sub_cert", "مستخلص مقاول باطن"),
                            ("retention", "رد محتجزات"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="المصدر",
                    ),
                ),
                ("source_url", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "قيد يومية",
                "verbose_name_plural": "قيود اليومية",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=300, verbose_name="البيان"),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=16, verbose_name="مدين"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=16, verbose_name="دائن"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        limit_choices_to={"is_group": False},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="accounting.account",
                        verbose_name="الحساب",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="accounting.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
