# Generated by Django 5.2.17 on 2026-10-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("contracting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="contracting.project",
                verbose_name="المشروع",
            ),
        ),
        migrations.AddField(
            model_name="journaltemplateline",
            name="account",
            field=models.ForeignKey(
                limit_choices_to={"is_group": False},
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.account",
                verbose_name="الحساب",
            ),
        ),
        migrations.AddField(
            model_name="journaltemplateline",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="accounting.journaltemplate",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="payable_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
                verbose_name="حساب دائن خاص (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="receivable_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
                verbose_name="حساب مدين خاص (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="accounting.partner",
                verbose_name="جهة التعامل",
            ),
        ),
        migrations.AddField(
            model_name="tax",
            name="purchase_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
                verbose_name="حساب المشتريات (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="tax",
            name="sale_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
                verbose_name="حساب المبيعات (اختياري)",
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["account", "entry"], name="accounting__account_e026d4_idx"
            ),
        ),
    ]
