# Generated by Django 5.2.17 on 2026-10-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                default="الخطوط المعدنية للمقاولات العامة",
                max_length=200,
                verbose_name="اسم الشركة",
            ),
        ),
    ]
