<?php defined('ABSPATH') || exit; include __DIR__ . '/_head.php'; ?>
<form class="filters card card-body py-2 mb-3"><div class="row g-2 align-items-end">
<div class="col-md-3"><label class="small">الحساب</label><select name="account" class="form-select form-select-sm searchable"><option value="">اختر الحساب</option><?php foreach ($accounts as $id => $n) : ?><option value="<?php echo (int) $id; ?>" <?php selected((string) ($account['id'] ?? ''), (string) $id); ?>><?php echo erp_e($n); ?></option><?php endforeach; ?></select></div>
<div class="col-auto"><label class="small">من</label><input type="date" name="date_from" value="<?php echo erp_a($date_from); ?>" class="form-control form-control-sm"></div>
<div class="col-auto"><label class="small">إلى</label><input type="date" name="date_to" value="<?php echo erp_a($date_to); ?>" class="form-control form-control-sm"></div>
<div class="col-md-2"><label class="small">جهة التعامل</label><select name="partner" class="form-select form-select-sm searchable"><option value="">الكل</option><?php foreach ($partners as $id => $n) : ?><option value="<?php echo (int) $id; ?>" <?php selected(ERP_UI::get('partner'), (string) $id); ?>><?php echo erp_e($n); ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><label class="small">المشروع</label><select name="project" class="form-select form-select-sm"><option value="">الكل</option><?php foreach ($projects as $id => $n) : ?><option value="<?php echo (int) $id; ?>" <?php selected(ERP_UI::get('project'), (string) $id); ?>><?php echo erp_e($n); ?></option><?php endforeach; ?></select></div>
<div class="col-auto"><button class="btn btn-sm btn-primary"><i class="bi bi-funnel"></i> عرض</button></div></div></form>
<?php if ($account) : ?><div class="card"><div class="card-header"><?php echo erp_e(ERP_Accounts::str($account)); ?></div><div class="table-responsive"><table class="table table-sm table-hover exportable">
<thead><tr><th>التاريخ</th><th>رقم القيد</th><th>المصدر</th><th>البيان</th><th>جهة التعامل</th><th class="num">مدين</th><th class="num">دائن</th><th class="num">الرصيد</th></tr></thead>
<tbody><tr class="table-light"><td colspan="7">رصيد أول المدة</td><td class="num fw-bold"><?php echo erp_e(erp_money0($opening)); ?></td></tr>
<?php foreach ($rows as $r) : $l = $r['line']; ?><tr class="clickable" data-href="<?php echo esc_url(home_url("/journal/{$l['entry_id']}/")); ?>"><td><?php echo erp_e(erp_date($l['entry_date'])); ?></td><td><?php echo erp_e($l['entry_number']); ?></td><td class="small"><?php echo erp_e(ERP_DB::display('journal_entry', 'source', $l['entry_source'])); ?></td><td class="small"><?php echo erp_e($l['label'] !== '' ? $l['label'] : $l['entry_memo']); ?></td><td class="small"><?php echo erp_e($l['partner_name'] ?? ''); ?></td><td class="num"><?php echo erp_e(erp_money($l['debit'])); ?></td><td class="num"><?php echo erp_e(erp_money($l['credit'])); ?></td><td class="num"><?php echo erp_e(erp_money0($r['balance'])); ?></td></tr><?php endforeach; ?></tbody>
<tfoot><tr><td colspan="5">الإجمالي / الرصيد الختامي</td><td class="num"><?php echo erp_e(erp_money($total_debit)); ?></td><td class="num"><?php echo erp_e(erp_money($total_credit)); ?></td><td class="num"><?php echo erp_e(erp_money0($closing)); ?></td></tr></tfoot></table></div></div>
<?php else : ?><div class="text-muted text-center py-5">اختر حساباً لعرض حركته</div><?php endif; ?>
