<?php defined('ABSPATH') || exit; include __DIR__ . '/_head.php'; ?>
<form class="filters card card-body py-2 mb-3" method="get" action="<?php echo esc_url(home_url('/reports/partner-statement/')); ?>"><div class="row g-2 align-items-end">
<div class="col-md-3"><label class="small">الجهة</label><select name="partner" class="form-select form-select-sm searchable"><option value="">اختر</option><?php foreach ($partners as $p) : ?><option value="<?php echo (int) $p['id']; ?>" <?php selected((string) ($partner['id'] ?? ''), (string) $p['id']); ?>><?php echo erp_e($p['name'] . ' (' . ERP_DB::display('partner', 'type', $p['type']) . ')'); ?></option><?php endforeach; ?></select></div>
<div class="col-auto"><label class="small">من</label><input type="date" name="date_from" value="<?php echo erp_a($date_from); ?>" class="form-control form-control-sm"></div>
<div class="col-auto"><label class="small">إلى</label><input type="date" name="date_to" value="<?php echo erp_a($date_to); ?>" class="form-control form-control-sm"></div>
<div class="col-auto form-check mt-4 ms-2"><input type="checkbox" class="form-check-input" name="all_accounts" value="1" id="aa" <?php checked(!empty($all_accounts)); ?>><label for="aa" class="form-check-label small">كل الحسابات</label></div>
<div class="col-auto"><button class="btn btn-sm btn-primary">عرض</button></div></div></form>
<?php if ($partner) : ?>
<div class="row g-3 mb-3"><?php foreach ($by_account as $b) : ?><div class="col-md-3"><div class="card card-body py-2"><div class="small text-muted"><?php echo erp_e($b['code'] . ' ' . $b['name']); ?></div><div class="fw-bold num">مدين <?php echo erp_e(erp_money0($b['d'])); ?> / دائن <?php echo erp_e(erp_money0($b['c'])); ?></div></div></div><?php endforeach; ?></div>
<div class="card"><div class="card-header">كشف حساب: <?php echo erp_e($partner['name']); ?></div><div class="table-responsive"><table class="table table-sm table-hover exportable">
<thead><tr><th>التاريخ</th><th>القيد</th><th>البيان</th><th>الحساب</th><th class="num">مدين</th><th class="num">دائن</th><th class="num">الرصيد</th></tr></thead>
<tbody><tr class="table-light"><td colspan="6">رصيد أول المدة</td><td class="num fw-bold"><?php echo erp_e(erp_money0($opening)); ?></td></tr>
<?php foreach ($rows as $r) : $l = $r['line']; ?><tr class="clickable" data-href="<?php echo esc_url($l['entry_source_url'] !== '' ? home_url($l['entry_source_url']) : home_url("/journal/{$l['entry_id']}/")); ?>"><td><?php echo erp_e(erp_date($l['entry_date'])); ?></td><td><?php echo erp_e($l['entry_number']); ?></td><td class="small"><?php echo erp_e($l['label'] !== '' ? $l['label'] : $l['entry_memo']); ?></td><td class="small"><?php echo erp_e($l['account_name']); ?></td><td class="num"><?php echo erp_e(erp_money($l['debit'])); ?></td><td class="num"><?php echo erp_e(erp_money($l['credit'])); ?></td><td class="num"><?php echo erp_e(erp_money0($r['balance'])); ?></td></tr><?php endforeach; ?></tbody>
<tfoot><tr><td colspan="4">الإجمالي / الرصيد</td><td class="num"><?php echo erp_e(erp_money($total_debit)); ?></td><td class="num"><?php echo erp_e(erp_money($total_credit)); ?></td><td class="num"><?php echo erp_e(erp_money0($closing)); ?></td></tr></tfoot></table></div></div>
<div class="small text-muted mt-2">الرصيد الموجب = مدين (مستحق لنا) • السالب بين أقواس = دائن (مستحق علينا)</div>
<?php endif; ?>
