# Generated by Django 5.2.17 on 2026-10-05 21:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BOQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=30, verbose_name="البند"),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="وصف البند"),
                ),
                (
                    "unit",
                    models.CharField(
                        default="م3", max_length=30, verbose_name="الوحدة"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="الكمية التعاقدية",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=16,
                        verbose_name="الفئة (سعر الوحدة)",
                    ),
                ),
                (
                    "is_variation",
                    models.BooleanField(
                        default=False, verbose_name="أعمال إضافية / أمر تغيير"
                    ),
                ),
            ],
            options={
                "verbose_name": "بند مقايسة",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("posted", "مرحّل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seq",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="رقم المستخلص بالعقد"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="الرقم"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاريخ المستخلص")),
                (
                    "period_from",
                    models.DateField(blank=True, null=True, verbose_name="الفترة من"),
                ),
                (
                    "period_to",
                    models.DateField(blank=True, null=True, verbose_name="الفترة إلى"),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="مستخلص ختامي"),
                ),
                (
                    "auto_deductions",
                    models.BooleanField(
                        default=True, verbose_name="احتساب الاستقطاعات تلقائياً"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="قيمة الأعمال الحالية",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="ضريبة القيمة المضافة",
                    ),
                ),
                (
                    "retention_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="ضمان أعمال (محتجزات)",
                    ),
                ),
                (
                    "advance_recovery",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="استرداد دفعة مقدمة",
                    ),
                ),
                (
                    "wht_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="ضريبة الخصم من المنبع",
                    ),
                ),
                (
                    "social_ins_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="تأمينات اجتماعية",
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="استقطاعات أخرى",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="صافي المستخلص المستحق",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                        verbose_name="القيد",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخلص",
                "verbose_name_plural": "المستخلصات",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CertificateDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="بيان الاستقطاع"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="المبلغ"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        limit_choices_to={"is_group": False},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.account",
                        verbose_name="الحساب",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deductions",
                        to="contracting.certificate",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CertificateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prev_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="الكمية السابقة",
                    ),
                ),
                (
                    "prev_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="القيمة السابقة",
                    ),
                ),
                (
                    "current_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="الكمية الحالية",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=16, verbose_name="الفئة"
                    ),
                ),
                (
                    "completion_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="تُطبق على الكمية التراكمية (مثلاً 70% لأعمال لم تكتمل) ويُستكمل الفرق تلقائياً في المستخلص التالي",
                        max_digits=6,
                        verbose_name="نسبة الصرف %",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="contracting.certificate",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cert_lines",
                        to="contracting.boqitem",
                        verbose_name="البند",
                    ),
                ),
            ],
            options={
                "ordering": ["item_id"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("client", "عقد مع العميل (المالك)"),
                            ("sub", "عقد مقاول باطن"),
                        ],
                        max_length=6,
                        verbose_name="نوع العقد",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="رقم العقد"
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="موضوع العقد")),
                ("date", models.DateField(verbose_name="تاريخ العقد")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ البدء"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "retention_pct",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("5"),
                        max_digits=6,
                        verbose_name="نسبة ضمان الأعمال (محتجزات) %",
                    ),
                ),
                (
                    "advance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="قيمة الدفعة المقدمة المتعاقد عليها",
                    ),
                ),
                (
                    "advance_recovery_pct",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=6,
                        verbose_name="نسبة استرداد الدفعة المقدمة من كل مستخلص %",
                    ),
                ),
                (
                    "social_ins_pct",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=6,
                        verbose_name="نسبة التأمينات الاجتماعية %",
                    ),
                ),
                (
                    "vat_on_net",
                    models.BooleanField(
                        default=False,
                        help_text="الافتراضي: الضريبة على إجمالي الأعمال الحالية",
                        verbose_name="احتساب ض.ق.م بعد خصم المحتجزات",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "ساري"),
                            ("closed", "منتهي (ختامي)"),
                            ("cancelled", "ملغي"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="شروط الدفع"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="accounting.partner",
                        verbose_name="العميل / مقاول الباطن",
                    ),
                ),
                (
                    "vat",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "vat"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.tax",
                        verbose_name="ضريبة القيمة المضافة",
                    ),
                ),
                (
                    "wht",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "wht"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.tax",
                        verbose_name="ضريبة الخصم من المنبع",
                    ),
                ),
            ],
            options={
                "verbose_name": "عقد",
                "verbose_name_plural": "العقود",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="certificate",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificates",
                to="contracting.contract",
                verbose_name="العقد",
            ),
        ),
        migrations.AddField(
            model_name="boqitem",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="contracting.contract",
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود المشروع"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المشروع")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="الموقع"),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مدير المشروع"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="الموازنة التقديرية للتكاليف",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ البدء"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء المتوقع"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "تحت الدراسة"),
                            ("active", "جاري التنفيذ"),
                            ("on_hold", "متوقف"),
                            ("completed", "منتهي - فترة ضمان"),
                            ("closed", "مغلق"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="accounting.partner",
                        verbose_name="المالك / العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشروع",
                "verbose_name_plural": "المشروعات",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="contracting.project",
                verbose_name="المشروع",
            ),
        ),
        migrations.CreateModel(
            name="RetentionRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("posted", "مرحّل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="الرقم"
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="المبلغ"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=300, verbose_name="البيان"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_releases",
                        to="contracting.contract",
                        verbose_name="العقد",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                        verbose_name="القيد",
                    ),
                ),
            ],
            options={
                "verbose_name": "رد محتجزات",
                "verbose_name_plural": "رد المحتجزات",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="certificate",
            unique_together={("contract", "seq")},
        ),
    ]
