# Generated by Django 5.2.17 on 2026-10-05 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("contracting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("posted", "مرحّل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sale", "فاتورة مبيعات"),
                            ("sale_return", "مردود مبيعات"),
                            ("purchase", "فاتورة مشتريات"),
                            ("purchase_return", "مردود مشتريات"),
                        ],
                        max_length=16,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="الرقم"
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الاستحقاق"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="مرجع / رقم فاتورة المورد",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="الإجمالي قبل الضريبة",
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="إجمالي الخصم",
                    ),
                ),
                (
                    "vat_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="ضريبة القيمة المضافة",
                    ),
                ),
                (
                    "wht_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="الخصم من المنبع",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="الصافي المستحق",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                        verbose_name="القيد",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="commerce.invoice",
                        verbose_name="الفاتورة الأصلية (للمرتجع)",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="accounting.partner",
                        verbose_name="العميل / المورد",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracting.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "wht",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "wht"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.tax",
                        verbose_name="خصم من المنبع",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة",
                "verbose_name_plural": "الفواتير",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("posted", "مرحّل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("receipt", "سند قبض"), ("payment", "سند صرف")],
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="الرقم"
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("partner", "على حساب جهة التعامل"),
                            ("advance", "دفعة مقدمة (عقد / مقاول)"),
                            ("account", "مباشر على حساب (مصروف / إيراد / أخرى)"),
                        ],
                        default="partner",
                        max_length=10,
                        verbose_name="نوع الحركة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="المبلغ"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "نقداً"),
                            ("transfer", "تحويل بنكي"),
                            ("cheque", "شيك"),
                            ("card", "بطاقة / محفظة"),
                        ],
                        default="cash",
                        max_length=10,
                        verbose_name="طريقة السداد",
                    ),
                ),
                (
                    "cheque_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم الشيك / المرجع"
                    ),
                ),
                (
                    "cheque_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ استحقاق الشيك"
                    ),
                ),
                (
                    "memo",
                    models.CharField(blank=True, max_length=300, verbose_name="البيان"),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="contracting.certificate",
                        verbose_name="سداد مستخلص",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="contracting.contract",
                        verbose_name="العقد",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "counter_account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_group": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="الحساب المقابل",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="commerce.invoice",
                        verbose_name="سداد فاتورة",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                        verbose_name="القيد",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="accounting.partner",
                        verbose_name="جهة التعامل",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracting.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "treasury",
                    models.ForeignKey(
                        limit_choices_to={
                            "is_group": False,
                            "kind__in": ["cash", "bank"],
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="الخزينة / البنك",
                    ),
                ),
            ],
            options={
                "verbose_name": "سند",
                "verbose_name_plural": "سندات القبض والصرف",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="الكود"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الصنف")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("stock", "صنف مخزني"),
                            ("service", "خدمة"),
                            ("consumable", "مستهلك (غير مخزني)"),
                        ],
                        default="stock",
                        max_length=12,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="عدد", max_length=30, verbose_name="الوحدة"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الباركود"
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="سعر البيع",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="سعر الشراء",
                    ),
                ),
                (
                    "min_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="حد الطلب",
                    ),
                ),
                (
                    "avg_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        editable=False,
                        max_digits=16,
                        verbose_name="متوسط التكلفة",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="حساب المصروف/التكلفة (اختياري)",
                    ),
                ),
                (
                    "income_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="حساب الإيراد (اختياري)",
                    ),
                ),
                (
                    "purchase_tax",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "vat"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.tax",
                        verbose_name="ضريبة الشراء",
                    ),
                ),
                (
                    "sale_tax",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "vat"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.tax",
                        verbose_name="ضريبة البيع",
                    ),
                ),
            ],
            options={
                "verbose_name": "صنف",
                "verbose_name_plural": "الأصناف",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="البيان"),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=14,
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=16, verbose_name="السعر"
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="خصم %"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_group": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.account",
                        verbose_name="الحساب",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="commerce.invoice",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracting.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "vat",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "vat"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.tax",
                        verbose_name="ض.ق.م",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commerce.product",
                        verbose_name="الصنف",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StockDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("posted", "مرحّل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("issue", "صرف مواد لمشروع"),
                            ("adj_in", "تسوية بالزيادة / رصيد أول المدة"),
                            ("adj_out", "تسوية بالعجز / هالك"),
                        ],
                        default="issue",
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="الرقم"
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "notes",
                    models.CharField(blank=True, max_length=300, verbose_name="البيان"),
                ),
                (
                    "counter_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="يُترك فارغاً لاستخدام الحساب الافتراضي من التوجيه المحاسبي",
                        limit_choices_to={"is_group": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="الحساب المقابل (اختياري)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                        verbose_name="القيد",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracting.project",
                        verbose_name="المشروع",
                    ),
                ),
            ],
            options={
                "verbose_name": "إذن مخزني",
                "verbose_name_plural": "الأذونات المخزنية",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="الكمية"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=16,
                        verbose_name="تكلفة الوحدة (للإضافة فقط)",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="commerce.stockdocument",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        limit_choices_to={"type": "stock"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commerce.product",
                        verbose_name="الصنف",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("posted", "مرحّل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=30, unique=True, verbose_name="الرقم"
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="المبلغ"
                    ),
                ),
                (
                    "memo",
                    models.CharField(blank=True, max_length=300, verbose_name="البيان"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_account",
                    models.ForeignKey(
                        limit_choices_to={"kind__in": ["cash", "bank"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="من خزينة/بنك",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                        verbose_name="القيد",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        limit_choices_to={"kind__in": ["cash", "bank"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                        verbose_name="إلى خزينة/بنك",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحويل نقدية",
                "verbose_name_plural": "التحويلات بين الخزائن والبنوك",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="الكود"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم المخزن")),
                ("active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracting.project",
                        verbose_name="مخزن موقع لمشروع",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخزن",
                "verbose_name_plural": "المخازن",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="الكمية"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=16,
                        verbose_name="تكلفة الوحدة",
                    ),
                ),
                ("doc_key", models.CharField(db_index=True, max_length=40)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("url", models.CharField(blank=True, max_length=200)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves",
                        to="commerce.product",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracting.project",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves",
                        to="commerce.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.AddField(
            model_name="stockdocument",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="commerce.warehouse",
                verbose_name="المخزن",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="commerce.warehouse",
                verbose_name="المخزن",
            ),
        ),
    ]
