# -*- coding: utf-8 -*-
"""المصادر الرسمية والمراجع المعتمدة. الروابط تشير إلى المواقع الرسمية للجهات المُصدِرة."""

STD, KSA, ISO, BOOK, CON = "المعايير الدولية (IFRS)", "الأنظمة والجهات السعودية", "معايير ISO", "كتب ومراجع مهنية", "عقود ومعايير الإنشاء"

SOURCES = [
    dict(id="conceptual", title="الإطار المفاهيمي للتقرير المالي (2018)", issuer="مجلس معايير المحاسبة الدولية IASB", type=STD,
         desc="الأساس الذي تُبنى عليه جميع المعايير: تعريف الأصل والالتزام والدخل والمصروف وخصائص المعلومات المفيدة.",
         url="https://www.ifrs.org/issued-standards/list-of-standards/conceptual-framework/"),
    dict(id="ias1", title="IAS 1 عرض القوائم المالية", issuer="IASB", type=STD,
         desc="مكونات القوائم المالية وتصنيف البنود متداولة وغير متداولة. (يحل محله IFRS 18 للفترات التي تبدأ من 1 يناير 2027).",
         url="https://www.ifrs.org/issued-standards/list-of-standards/ias-1-presentation-of-financial-statements/"),
    dict(id="ifrs18", title="IFRS 18 العرض والإفصاح في القوائم المالية", issuer="IASB", type=STD,
         desc="صدر في أبريل 2024 ويسري من 1 يناير 2027؛ يعيد تنظيم قائمة الدخل في فئات (تشغيلية، استثمار، تمويل).",
         url="https://www.ifrs.org/issued-standards/list-of-standards/ifrs-18-presentation-and-disclosure-in-financial-statements/"),
    dict(id="ifrs15", title="IFRS 15 الإيراد من العقود مع العملاء", issuer="IASB", type=STD,
         desc="المعيار الأساسي لمحاسبة المقاولات: نموذج الخطوات الخمس، الاعتراف بالإيراد عبر الزمن، قياس التقدم، أصول والتزامات العقد، تعديلات العقد.",
         url="https://www.ifrs.org/issued-standards/list-of-standards/ifrs-15-revenue-from-contracts-with-customers/"),
    dict(id="ias37", title="IAS 37 المخصصات والالتزامات والأصول المحتملة", issuer="IASB", type=STD,
         desc="العقود المتوقع خسارتها (Onerous Contracts) ومخصصات الضمان والغرامات والقضايا.",
         url="https://www.ifrs.org/issued-standards/list-of-standards/ias-37-provisions-contingent-liabilities-and-contingent-assets/"),
    dict(id="ias16", title="IAS 16 العقارات والآلات والمعدات", issuer="IASB", type=STD,
         desc="الاعتراف بالمعدات وقياسها وإهلاكها ومراجعة العمر الإنتاجي والقيمة المتبقية.",
         url="https://www.ifrs.org/issued-standards/list-of-standards/ias-16-property-plant-and-equipment/"),
    dict(id="ifrs16", title="IFRS 16 عقود الإيجار", issuer="IASB", type=STD,
         desc="محاسبة استئجار المعدات والمكاتب والسكن العمالي: أصل حق الاستخدام والتزام الإيجار والإعفاءات.",
         url="https://www.ifrs.org/issued-standards/list-of-standards/ifrs-16-leases/"),
    dict(id="ias2", title="IAS 2 المخزون", issuer="IASB", type=STD,
         desc="قياس المخزون بالتكلفة أو صافي القيمة القابلة للتحقق أيهما أقل وطرق التسعير.",
         url="https://www.ifrs.org/issued-standards/list-of-standards/ias-2-inventories/"),
    dict(id="ias23", title="IAS 23 تكاليف الاقتراض", issuer="IASB", type=STD,
         desc="رسملة تكاليف الاقتراض المرتبطة مباشرة بالأصول المؤهلة.",
         url="https://www.ifrs.org/issued-standards/list-of-standards/ias-23-borrowing-costs/"),
    dict(id="ifrs9", title="IFRS 9 الأدوات المالية", issuer="IASB", type=STD,
         desc="الخسائر الائتمانية المتوقعة على العملاء والمحتجزات وأصول العقود.",
         url="https://www.ifrs.org/issued-standards/list-of-standards/ifrs-9-financial-instruments/"),
    dict(id="ias7", title="IAS 7 قائمة التدفقات النقدية", issuer="IASB", type=STD,
         desc="تصنيف التدفقات النقدية إلى تشغيلية واستثمارية وتمويلية.",
         url="https://www.ifrs.org/issued-standards/list-of-standards/ias-7-statement-of-cash-flows/"),
    dict(id="ifrs_sme", title="المعيار الدولي للمنشآت الصغيرة والمتوسطة (IFRS for SMEs)", issuer="IASB", type=STD,
         desc="بديل مبسّط للمنشآت التي لا تخضع للمساءلة العامة، ويطبَّق في المملكة على كثير من شركات المقاولات المتوسطة.",
         url="https://www.ifrs.org/issued-standards/ifrs-for-smes/"),

    dict(id="socpa", title="الهيئة السعودية للمراجعين والمحاسبين (SOCPA)", issuer="SOCPA", type=KSA,
         desc="الجهة المسؤولة عن اعتماد المعايير الدولية في المملكة وإصدار متطلبات الإفصاح الإضافية وبرامج الزمالة المهنية.",
         url="https://socpa.org.sa"),
    dict(id="zatca", title="هيئة الزكاة والضريبة والجمارك (ZATCA)", issuer="ZATCA", type=KSA,
         desc="الأنظمة واللوائح والأدلة الإرشادية للزكاة وضريبة القيمة المضافة وضريبة الاستقطاع والفوترة الإلكترونية.",
         url="https://zatca.gov.sa"),
    dict(id="vat_law", title="نظام ضريبة القيمة المضافة ولائحته التنفيذية", issuer="ZATCA", type=KSA,
         desc="النسبة الأساسية 15% منذ 1 يوليو 2020، تاريخ الاستحقاق، الفاتورة الضريبية، ومدد حفظ السجلات.",
         url="https://zatca.gov.sa/ar/RulesRegulations/Taxes/Pages/default.aspx"),
    dict(id="zakat_reg", title="اللائحة التنفيذية لجباية الزكاة", issuer="ZATCA", type=KSA,
         desc="تحديد الوعاء الزكوي والإضافات والحسميات وإجراءات الإقرار الزكوي.",
         url="https://zatca.gov.sa/ar/RulesRegulations/Zakat/Pages/default.aspx"),
    dict(id="fatoora", title="الفوترة الإلكترونية (فاتورة)", issuer="ZATCA", type=KSA,
         desc="المرحلة الأولى (الإصدار) من 4 ديسمبر 2021، والمرحلة الثانية (الربط والتكامل) على موجات بدأت من 1 يناير 2023.",
         url="https://zatca.gov.sa/ar/E-Invoicing/Pages/default.aspx"),
    dict(id="companies_law", title="نظام الشركات (1443هـ)", issuer="وزارة التجارة", type=KSA,
         desc="نافذ منذ 19 يناير 2023: القوائم المالية السنوية، الاحتياطيات، مسؤوليات المديرين ومراجع الحسابات.",
         url="https://mc.gov.sa"),
    dict(id="books_law", title="نظام الدفاتر التجارية", issuer="وزارة التجارة", type=KSA,
         desc="التزامات التاجر بمسك الدفاتر والسجلات وحفظها والمستندات المؤيدة لها للمدة النظامية.",
         url="https://laws.boe.gov.sa"),
    dict(id="boe", title="بوابة الأنظمة — هيئة الخبراء بمجلس الوزراء", issuer="هيئة الخبراء", type=KSA,
         desc="المرجع الرسمي للنصوص المحدّثة لجميع الأنظمة السعودية.",
         url="https://laws.boe.gov.sa"),
    dict(id="civil_law", title="نظام المعاملات المدنية (1444هـ)", issuer="هيئة الخبراء بمجلس الوزراء", type=KSA,
         desc="أحكام عقد المقاولة ومسؤولية المقاول والمهندس عن سلامة المباني (الضمان العشري)، وهو سبب رئيسي لطول مدة حفظ ملفات المشروعات.",
         url="https://laws.boe.gov.sa"),
    dict(id="gtpl", title="نظام المنافسات والمشتريات الحكومية ولائحته التنفيذية", issuer="وزارة المالية", type=KSA,
         desc="ينظم العقود الحكومية: الضمان الابتدائي والنهائي، الدفعات المقدمة، أوامر التغيير، الغرامات، والاستلام.",
         url="https://www.mof.gov.sa"),
    dict(id="etimad", title="منصة اعتماد", issuer="وزارة المالية", type=KSA,
         desc="المنصة الحكومية الإلكترونية للمنافسات والعقود والمستخلصات والضمانات البنكية الإلكترونية.",
         url="https://etimad.sa"),
    dict(id="pdpl", title="نظام حماية البيانات الشخصية", issuer="سدايا (SDAIA)", type=KSA,
         desc="ضوابط جمع ومعالجة وحفظ البيانات الشخصية للموظفين والعملاء ومدد الاحتفاظ بها.",
         url="https://sdaia.gov.sa"),
    dict(id="nca_ecc", title="الضوابط الأساسية للأمن السيبراني (ECC)", issuer="الهيئة الوطنية للأمن السيبراني", type=KSA,
         desc="ضوابط النسخ الاحتياطي وإدارة الصلاحيات وحماية البيانات — مرجع لأفضل الممارسات في الأرشفة الإلكترونية.",
         url="https://nca.gov.sa"),
    dict(id="gosi", title="المؤسسة العامة للتأمينات الاجتماعية", issuer="GOSI", type=KSA,
         desc="اشتراكات العاملين في مواقع المشروعات وتسجيلها محاسبياً.",
         url="https://www.gosi.gov.sa"),
    dict(id="mol", title="نظام العمل — وزارة الموارد البشرية", issuer="وزارة الموارد البشرية والتنمية الاجتماعية", type=KSA,
         desc="الأجور، مكافأة نهاية الخدمة، حماية الأجور (مُدد)، وسجلات العاملين.",
         url="https://www.hrsd.gov.sa"),

    dict(id="fidic", title="عقود فيديك FIDIC (الكتاب الأحمر 2017 وغيره)", issuer="الاتحاد الدولي للمهندسين الاستشاريين", type=CON,
         desc="الشروط النموذجية لعقود الإنشاء: الدفعات المرحلية، المحتجزات، الدفعة المقدمة، التغييرات والمطالبات وشهادات الاستلام.",
         url="https://fidic.org"),
    dict(id="iso19650", title="ISO 19650 إدارة المعلومات في المشروعات الإنشائية (BIM)", issuer="ISO", type=ISO,
         desc="بيئة البيانات المشتركة (CDE) وحالات المستندات (قيد العمل، مشترك، منشور، مؤرشف) وتسمية الملفات.",
         url="https://www.iso.org/standard/68078.html"),
    dict(id="iso15489", title="ISO 15489-1:2016 إدارة السجلات", issuer="ISO", type=ISO,
         desc="المبادئ الدولية لإنشاء السجلات وتصنيفها وحفظها والتخلص منها بطريقة منضبطة.",
         url="https://www.iso.org/standard/62542.html"),
    dict(id="iso9001", title="ISO 9001:2015 — البند 7.5 المعلومات الموثقة", issuer="ISO", type=ISO,
         desc="ضبط الوثائق: الإصدار والمراجعة والاعتماد والتوزيع والحماية والاحتفاظ.",
         url="https://www.iso.org/standard/62085.html"),
    dict(id="coso", title="إطار COSO للرقابة الداخلية (2013)", issuer="COSO", type=BOOK,
         desc="المكونات الخمسة للرقابة الداخلية والمبادئ السبعة عشر؛ أساس تصميم إجراءات الضبط في الشركات.",
         url="https://www.coso.org"),
    dict(id="pmi", title="دليل PMBOK وممارسات إدارة القيمة المكتسبة", issuer="معهد إدارة المشروعات PMI", type=BOOK,
         desc="مؤشرات أداء التكلفة والجدول الزمني (CPI, SPI) والتقدير عند الإنجاز (EAC).",
         url="https://www.pmi.org"),
    dict(id="peterson", title="Construction Accounting and Financial Management", issuer="Steven J. Peterson — Pearson", type=BOOK,
         desc="مرجع جامعي متخصص في محاسبة وإدارة مالية شركات المقاولات.",
         url="https://www.pearson.com"),
    dict(id="kieso", title="Intermediate Accounting — IFRS Edition", issuer="Kieso, Weygandt & Warfield — Wiley", type=BOOK,
         desc="المرجع الأكاديمي الأشهر لأساسيات المحاسبة المالية وفق IFRS.",
         url="https://www.wiley.com"),
]
